### PR TITLE
Feature/contrib

### PR DESCRIPTION
**Pull request by hickey**
The enclosed files allows one to build binary packages for RedHat/CentOS or Debian/Ubuntu Linux distributions.

### CODE REVIEW

**Comment by hickey** [comment]
Has this even been looked at?  I would like to close this out of my lists of PRs so I don't have to think about it any more. 

It just adds the build files for RPM and DEB packaging. 

Thanks.

**Comment by millerjs** [comment]
@hickey thanks for poking this issue, I'll take a look as soon as I get a chance

**Comment by hickey** [comment]
Poke... poke.... poke  :-)

**Comment by millerjs** [comment]
@hickey Thank you for your persistence on the issue. I am closing this PR in preference for maintainability over feature completeness.

**Pull request closed without merging**
